source 'https://rubygems.org'
ruby '1.9.3'

gem 'bundler', '>1.2.0'
gem 'sinatra'
gem 'pg'
#gem 'datamapper'
gem 'dm-core'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-postgres-adapter'
gem 'rack-flash3'
gem 'httparty'
gem 'haml'
gem 'haml-contrib'
gem 'tzinfo'
gem 'ri_cal'
gem 'chronic'
gem 'rdiscount'
gem 'puma'

group :development do
  gem 'dm-sqlite-adapter'
  gem 'growl'
  gem 'guard', '~> 2'
  gem 'guard-bundler'
  gem 'guard-puma'

  gem 'pry'
  gem 'binding_of_caller'
  gem 'better_errors'
end
