source 'https://rubygems.org'

gem 'sinatra'
gem 'datamapper'
gem 'dm-core'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
gem 'rack-flash3'
gem 'httparty'
gem 'haml'
gem 'haml-contrib'
gem 'tzinfo'
gem 'ri_cal'
gem 'chronic'
gem 'rdiscount'

gem 'growl'
gem 'guard', '~> 2'
gem 'guard-bundler'
gem 'guard-puma'

gem 'pry'
gem 'binding_of_caller'
gem 'better_errors'
